apiVersion: v1
kind: Service
metadata:
  name: neural-fabric
  namespace: codex-warlab
  annotations:
    service.istio.io/canonical-name: neural-fabric
spec:
  selector:
    app.kubernetes.io/name: neural-fabric
  ports:
    - name: http
      port: 8092
      targetPort: 8092
  type: ClusterIP