#!/usr/bin/env bash
set -euo pipefail

# CodexImmortal War Lab dependency scaffold
# Adds minimal requirements.txt and package.json stubs for apps and packages.

ROOT="${1:-.}"
cd "$ROOT"

echo "[CodexImmortal] Adding dependency stubs under $ROOT" 

mktext() {
  local path="$1"
  local dir
  dir="$(dirname "$path")"
  mkdir -p "$dir"
  cat > "$path" << EOF
# Generated by deps-setup.sh
# Fill with real pinned versions for your environment.
EOF
}

mkjson() {
  local path="$1"
  local dir
  dir="$(dirname "$path")"
  mkdir -p "$dir"
  cat > "$path" << EOF
{
  "name": "$(basename "$dir")",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "echo 'TODO: wire real start script'",
    "test": "echo 'TODO: add tests'"
  },
  "dependencies": {},
  "devDependencies": {}
}
EOF
}

# Python packages requirements
for pkg in \
  packages/shared-core \
  packages/pqc-utils \
  packages/storage-mesh \
  packages/neural-fabric \
  packages/nft-attestation \
  packages/playbook-engine \
  packages/osint-fusion \
  packages/integration; do
  mktext "$pkg/requirements.txt"
  mktext "$pkg/pyproject.toml"
done

# Python apps requirements
for app in sentinel-api strategist-graph archivist-memory executor-orchestrator threat-board-api; do
  mktext "apps/$app/requirements.txt"
  mktext "apps/$app/pyproject.toml"
done

# Dashboard JS project
mkjson apps/dashboard/package.json
mkjson apps/dashboard/package-lock.json

# Root dev utilities
mktext requirements-dev.txt
mkjson package.json

cat << EOF
[CodexImmortal] Dependency stubs created.
Next:
  - Replace placeholders with real pinned versions.
  - Align Python tools (ruff, mypy, pytest) with ci.yml.
  - Wire dashboard scripts to your chosen bundler (Vite, CRA, Next).
EOF