#!/usr/bin/env bash
set -euo pipefail

# CodexImmortal Agentic War Lab setup script
# Creates directory tree and empty placeholder files for the private server monorepo.

ROOT="${1:-codeximmortal-warlab}"

mkdir -p "$ROOT"
cd "$ROOT"

echo "[CodexImmortal] Initializing monorepo at $ROOT" 

# Helper to create file with header if missing
mkfile() {
  local path="$1"
  local dir
  dir="$(dirname "$path")"
  mkdir -p "$dir"
  if [ ! -f "$path" ]; then
    cat > "$path" << 'EOF'
# CODEXIMMORTAL AGENTIC AI NFT WAR LAB
# Placeholder file generated by setup.sh
# Fill with implementation according to CodexImmortal architecture.
EOF
  fi
}

# Root files
mkfile README.md
mkfile .gitignore
mkfile .env.example
mkfile docker-compose.yml
mkfile warlabcore.py

# GitHub workflows
mkfile .github/workflows/ci.yml
mkfile .github/workflows/deploy-staging.yml
mkfile .github/workflows/nft-mint.yml
mkfile .github/workflows/security-audit.yml

# Apps
for app in sentinel-api strategist-graph archivist-memory executor-orchestrator threat-board-api dashboard; do
  mkfile "apps/$app/main.py"
  mkfile "apps/$app/__init__.py"
  mkfile "apps/$app/README.md"
  if [ "$app" != "dashboard" ]; then
    mkfile "apps/$app/routes.py"
    mkfile "apps/$app/service.py"
  fi
done
mkfile apps/strategist-graph/graph.py
mkfile apps/strategist-graph/mitre_map.json
mkfile apps/archivist-memory/api.py
mkfile apps/executor-orchestrator/runner.py
mkfile apps/threat-board-api/ws.py

# Packages: shared-core
mkfile packages/shared-core/__init__.py
mkfile packages/shared-core/models.py
mkfile packages/shared-core/settings.py
mkfile packages/shared-core/logging.py

# Packages: pqc-utils
mkfile packages/pqc-utils/__init__.py
mkfile packages/pqc-utils/kem.py
mkfile packages/pqc-utils/signing.py
mkfile packages/pqc-utils/tls.py
mkfile packages/pqc-utils/rotation.py
mkfile packages/pqc-utils/vault.py
mkfile packages/pqc-utils/messagebus.py
mkfile packages/pqc-utils/channel.py

# Packages: storage-mesh
mkfile packages/storage-mesh/__init__.py
mkfile packages/storage-mesh/classifier.py
mkfile packages/storage-mesh/sealer.py
mkfile packages/storage-mesh/sharding.py
mkfile packages/storage-mesh/distributor.py
mkfile packages/storage-mesh/integrity.py
mkfile packages/storage-mesh/recovery.py
mkfile packages/storage-mesh/policyengine.py
mkfile packages/storage-mesh/tamperdetection.py
mkfile packages/storage-mesh/tests/test_storagemesh.py

# Packages: neural-fabric core
mkfile packages/neural-fabric/__init__.py
mkfile packages/neural-fabric/state.py
mkfile packages/neural-fabric/consensus.py
mkfile packages/neural-fabric/graph.py
mkfile packages/neural-fabric/runner.py
mkfile packages/neural-fabric/adversarialshield.py
mkfile packages/neural-fabric/telemetry.py
mkfile packages/neural-fabric/humangate.py

# Neural-fabric nodes
for node in sentinel strategist archivist executor; do
  mkfile "packages/neural-fabric/nodes/$node.py"
done

# Neural-fabric memory
mkfile packages/neural-fabric/memory/__init__.py
mkfile packages/neural-fabric/memory/memorygraphstore.py
mkfile packages/neural-fabric/memory/memoryembeddings.py
mkfile packages/neural-fabric/memory/memorydecay.py
mkfile packages/neural-fabric/memory/memorysync.py

# Neural-fabric learning
mkfile packages/neural-fabric/learning/__init__.py
mkfile packages/neural-fabric/learning/collector.py
mkfile packages/neural-fabric/learning/curator.py
mkfile packages/neural-fabric/learning/batchmanager.py
mkfile packages/neural-fabric/learning/finetuner.py
mkfile packages/neural-fabric/learning/rollback.py

# Packages: nft-attestation
mkfile packages/nft-attestation/__init__.py
mkfile packages/nft-attestation/metadatabuilder.py
mkfile packages/nft-attestation/minter.py
mkfile packages/nft-attestation/custody.py

# Packages: playbook-engine
mkfile packages/playbook-engine/__init__.py
mkfile packages/playbook-engine/schema.py
mkfile packages/playbook-engine/executor.py
mkfile packages/playbook-engine/triggerengine.py
mkfile packages/playbook-engine/blastradius.py
for f in storageactions cryptoactions agentactions nftactions networkactions; do
  mkfile "packages/playbook-engine/actions/${f}.py"
done
mkfile packages/playbook-engine/library/lockdownlattice.yaml
mkfile packages/playbook-engine/library/sovereignrestore.yaml
mkfile packages/playbook-engine/library/trustpurge.yaml
mkfile packages/playbook-engine/library/modelisolation.yaml
mkfile packages/playbook-engine/library/shardrebalance.yaml

# Packages: osint-fusion
mkfile packages/osint-fusion/__init__.py
mkfile packages/osint-fusion/connectors.py
mkfile packages/osint-fusion/router.py

# Packages: integration
mkfile packages/integration/__init__.py
mkfile packages/integration/web3storage.py
mkfile packages/integration/identitybridge.py
mkfile packages/integration/apigateway.py
mkfile packages/integration/notifications.py
mkfile packages/integration/federation/__init__.py
mkfile packages/integration/federation/mesh.py

# Configs core
mkfile configs/settings.py
mkfile configs/vault_loader.py
mkfile configs/validator.py

# Config profiles
for env in dev staging production airgap; do
  mkfile "configs/profiles/${env}.env"
done

# Policy files
for ring in unclass sensitive classified topsecret ts_sci; do
  mkfile "configs/policies/${ring}.yaml"
done

# Agent configs
for agent in sentinel strategist archivist executor; do
  mkfile "configs/agents/${agent}.yaml"
done

# Model configs
mkfile configs/models/ollama.yaml
mkfile configs/models/vllm.yaml

# Network and storage configs
mkfile configs/network/messagebus.yaml
mkfile configs/network/tls.yaml
mkfile configs/storage/rings.yaml

# Infra: docker, k8s, tls, otel, grafana, istio
mkfile infra/docker/README.md
mkfile infra/k8s/namespace.yaml
mkfile infra/k8s/network-policies.yaml
mkfile infra/k8s/vault-agent-injector.yaml
mkfile infra/k8s/spire-server.yaml
mkfile infra/k8s/spire-agent.yaml
mkfile infra/k8s/ingress.yaml
mkfile infra/k8s/monitoring/servicemonitor.yaml
mkfile infra/tls/nginx.conf
mkfile infra/tls/Caddyfile
mkfile infra/tls/generate_pqc_certs.sh
mkfile infra/otel/otel-collector-config.yaml
mkfile infra/grafana/dashboards/warlab-overview.json
mkfile infra/istio/peer-authentication.yaml

# Docs: module specs & runbooks
for f in 0101PQCARCH 0202KEYROTATION 0303SHARDVAULT 0404THREATBOARD 0505REDTEAM 0606ZKPROOF 0707NFTMINT 0808AIPIPELINE 0909OSINTFUSION 1010FEDERATEDNODE 1111SOVEREIGNDATABASE 1212CODINGTUTOR; do
  mkfile "docs/modules/${f}.md"
done
mkfile docs/runbooks/operations.md
mkfile docs/runbooks/incidents.md
mkfile docs/runbooks/playbooks.md
mkfile docs/diagrams/architecture.md

# Runtime dirs (no files)
mkdir -p data/postgres data/redis data/ipfs data/vector data/registry
mkdir -p logs/api logs/agents logs/audit logs/security logs/otel
mkdir -p backups/snapshots backups/shards backups/config backups/memory-graph
mkdir -p artifacts/nft artifacts/proofs artifacts/reports artifacts/manifests
mkdir -p secrets

# Scripts
mkfile scripts/quantumthreatscan.py
mkfile scripts/keyceremony.py
mkfile scripts/deaddropvault.py
mkfile scripts/codexconsole.py
mkfile scripts/redteam/redteam_nft_vault_tests.py
mkfile scripts/redteam/redteam_storage_mesh_tests.py
mkfile scripts/redteam/redteam_agent_consensus_tests.py
mkfile scripts/redteam/redteam_pqc_tests.py
mkfile scripts/redteam/redteam_runner.py
mkfile scripts/simulation/scenario_builder.py
mkfile scripts/simulation/adversary_emulator.py
mkfile scripts/simulation/observer.py
mkfile scripts/simulation/report_generator.py
mkfile scripts/simulation/runner.py

# Final message
cat << EOF
[CodexImmortal] Directory scaffold created.
Root: $(pwd)
Next:
  - Fill package and app files with implementations.
  - Wire configs to services.
  - Add dependency files (requirements.txt, package.json) per package.
EOF